import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// The project root is resolved relative to this script so the command works from any working directory.
const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const envPath = path.join(projectRoot, ".env");
const outputPath = path.join(projectRoot, "js", "env.js");

// Only public values should ever be copied into the browser-readable output file.
const PUBLIC_KEYS = ["SUPABASE_URL", "SUPABASE_ANON_KEY"];

// Lightweight .env parsing is enough here because only simple key=value pairs are needed.
function parseEnvFile(source) {
  const values = {};

  source.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      return;
    }

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex === -1) {
      return;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  });

  return values;
}

// The generated file intentionally exports nothing and just seeds a window global for browser scripts.
function buildBrowserEnv(values) {
  const publicValues = {};

  PUBLIC_KEYS.forEach((key) => {
    publicValues[key] = values[key] || "";
  });

  return [
    "// This file is generated by scripts/generate-env.mjs. Do not edit it manually.",
    "window.__PUBLIC_ENV__ = " + JSON.stringify(publicValues, null, 2) + ";",
    ""
  ].join("\n");
}

if (!fs.existsSync(envPath)) {
  // Failing loudly here is better than silently generating an empty config and breaking auth in the browser.
  throw new Error("Missing .env file. Copy .env.example to .env and fill in your Supabase public keys first.");
}

// The browser-readable file is regenerated from `.env` every time the script runs.
const envValues = parseEnvFile(fs.readFileSync(envPath, "utf8"));
fs.writeFileSync(outputPath, buildBrowserEnv(envValues), "utf8");
console.log("Generated js/env.js from .env");
