create extension if not exists pgcrypto;

create schema if not exists private;

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  user_id uuid not null references public.users(id) on delete cascade,
  subject text not null check (char_length(trim(subject)) between 3 and 120),
  category text not null default 'GENERAL' check (category in ('GENERAL', 'CHALLENGE', 'ACCOUNT', 'SCORING', 'BUG')),
  priority text not null default 'NORMAL' check (priority in ('LOW', 'NORMAL', 'HIGH')),
  status text not null default 'OPEN' check (status in ('OPEN', 'ACCEPTED', 'ANSWERED', 'CLOSED')),
  accepted_by uuid references public.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_message_at timestamptz not null default timezone('utc', now()),
  admin_last_replied_at timestamptz,
  user_last_replied_at timestamptz,
  message_count integer not null default 0 check (message_count >= 0)
);

create table if not exists public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_id uuid not null references public.users(id) on delete cascade,
  author_role text not null check (author_role in ('user', 'admin')),
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists support_tickets_user_id_idx
  on public.support_tickets(user_id);

create index if not exists support_tickets_last_message_at_idx
  on public.support_tickets(last_message_at desc);

create index if not exists support_tickets_status_idx
  on public.support_tickets(status);

create index if not exists support_ticket_messages_ticket_id_idx
  on public.support_ticket_messages(ticket_id, created_at);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

create or replace function private.set_support_ticket_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

create or replace function private.apply_support_ticket_message_effects()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  update public.support_tickets
  set
    updated_at = coalesce(new.created_at, timezone('utc', now())),
    last_message_at = coalesce(new.created_at, timezone('utc', now())),
    message_count = message_count + 1,
    admin_last_replied_at = case
      when new.author_role = 'admin' then coalesce(new.created_at, timezone('utc', now()))
      else admin_last_replied_at
    end,
    user_last_replied_at = case
      when new.author_role = 'user' then coalesce(new.created_at, timezone('utc', now()))
      else user_last_replied_at
    end,
    status = case
      when status = 'CLOSED' then 'CLOSED'
      when new.author_role = 'admin' then 'ANSWERED'
      else 'OPEN'
    end
  where id = new.ticket_id;

  return new;
end;
$$;

drop trigger if exists support_tickets_set_updated_at on public.support_tickets;
create trigger support_tickets_set_updated_at
before update on public.support_tickets
for each row
execute function private.set_support_ticket_updated_at();

drop trigger if exists support_ticket_messages_apply_effects on public.support_ticket_messages;
create trigger support_ticket_messages_apply_effects
after insert on public.support_ticket_messages
for each row
execute function private.apply_support_ticket_message_effects();

create policy "support_tickets_select_own_or_admin"
on public.support_tickets
for select
to authenticated
using (
  (select auth.uid()) is not null
  and (
    user_id = (select auth.uid())
    or exists (
      select 1
      from public.users u
      where u.id = (select auth.uid())
        and u.is_admin = true
    )
  )
);

create policy "support_tickets_insert_own"
on public.support_tickets
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

create policy "support_tickets_update_admin_only"
on public.support_tickets
for update
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = (select auth.uid())
      and u.is_admin = true
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = (select auth.uid())
      and u.is_admin = true
  )
);

create policy "support_ticket_messages_select_own_or_admin"
on public.support_ticket_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.support_tickets t
    where t.id = support_ticket_messages.ticket_id
      and (
        t.user_id = (select auth.uid())
        or exists (
          select 1
          from public.users u
          where u.id = (select auth.uid())
            and u.is_admin = true
        )
      )
  )
);

create policy "support_ticket_messages_insert_participants"
on public.support_ticket_messages
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and author_id = (select auth.uid())
  and exists (
    select 1
    from public.support_tickets t
    where t.id = support_ticket_messages.ticket_id
      and t.status <> 'CLOSED'
      and (
        (support_ticket_messages.author_role = 'user' and t.user_id = (select auth.uid()))
        or (
          support_ticket_messages.author_role = 'admin'
          and exists (
            select 1
            from public.users u
            where u.id = (select auth.uid())
              and u.is_admin = true
          )
        )
      )
  )
);

alter publication supabase_realtime add table public.support_tickets;
alter publication supabase_realtime add table public.support_ticket_messages;
